-- MySQL Script generated by MySQL Workbench
-- Sun Mar  5 00:16:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema laquena
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laquena
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laquena` DEFAULT CHARACTER SET utf8 ;
USE `laquena` ;

-- -----------------------------------------------------
-- Table `laquena`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`country` (
  `iso31661Code` VARCHAR(2) NOT NULL,
  `name` VARCHAR(70) NULL,
  PRIMARY KEY (`iso31661Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`establecimiento` (
  `establecimientoId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `legalName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `manager` VARCHAR(45) NULL,
  `iso31661Code` VARCHAR(2) NOT NULL,
  `streetAdress` VARCHAR(45) NULL,
  `addressRegion` VARCHAR(45) NULL,
  `adressLocality` VARCHAR(45) NULL,
  `latitude` DECIMAL(11,7) NULL,
  `longitude` DECIMAL(11,7) NULL,
  `ratingValue` DECIMAL(3,2) NULL,
  `ratingCount` INT NULL,
  PRIMARY KEY (`establecimientoId`),
  INDEX `fk_Establecimiento_country_idx` (`iso31661Code` ASC),
  CONSTRAINT `fk_Establecimiento_country`
    FOREIGN KEY (`iso31661Code`)
    REFERENCES `laquena`.`country` (`iso31661Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`openingHour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`openingHour` (
  `openingHourId` INT NOT NULL AUTO_INCREMENT,
  `establecimientoId` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  INDEX `fk_OpeningHour_Establecimiento1_idx` (`establecimientoId` ASC),
  UNIQUE INDEX `Description_UNIQUE` (`description` ASC),
  UNIQUE INDEX `establecimientoId_UNIQUE` (`establecimientoId` ASC),
  PRIMARY KEY (`openingHourId`),
  CONSTRAINT `fk_OpeningHour_Establecimiento1`
    FOREIGN KEY (`establecimientoId`)
    REFERENCES `laquena`.`establecimiento` (`establecimientoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`phoneList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`phoneList` (
  `establecimientoId` INT NOT NULL,
  `phone` VARCHAR(12) NOT NULL,
  INDEX `fk_PhoneList_Establecimiento1_idx` (`establecimientoId` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `establecimientoId_UNIQUE` (`establecimientoId` ASC),
  CONSTRAINT `fk_PhoneList_Establecimiento1`
    FOREIGN KEY (`establecimientoId`)
    REFERENCES `laquena`.`establecimiento` (`establecimientoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`currency` (
  `idCurrency` VARCHAR(3) NOT NULL,
  `description` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idCurrency`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`establecimiento_currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`establecimiento_currency` (
  `establecimientoId` INT NOT NULL,
  `idCurrency` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`establecimientoId`, `idCurrency`),
  INDEX `fk_Establecimiento_has_Currency_Currency1_idx` (`idCurrency` ASC),
  INDEX `fk_Establecimiento_has_Currency_Establecimiento1_idx` (`establecimientoId` ASC),
  CONSTRAINT `fk_Establecimiento_has_Currency_Establecimiento1`
    FOREIGN KEY (`establecimientoId`)
    REFERENCES `laquena`.`establecimiento` (`establecimientoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Establecimiento_has_Currency_Currency1`
    FOREIGN KEY (`idCurrency`)
    REFERENCES `laquena`.`currency` (`idCurrency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`payMehtod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`payMehtod` (
  `payMehtodId` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`payMehtodId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`establecimiento_payMehtod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`establecimiento_payMehtod` (
  `establecimientoId` INT NOT NULL,
  `payMehtodId` INT NOT NULL,
  PRIMARY KEY (`establecimientoId`, `payMehtodId`),
  INDEX `fk_establecimiento_has_PayMehtod_PayMehtod1_idx` (`payMehtodId` ASC),
  INDEX `fk_establecimiento_has_PayMehtod_establecimiento1_idx` (`establecimientoId` ASC),
  CONSTRAINT `fk_establecimiento_has_PayMehtod_establecimiento1`
    FOREIGN KEY (`establecimientoId`)
    REFERENCES `laquena`.`establecimiento` (`establecimientoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_establecimiento_has_PayMehtod_PayMehtod1`
    FOREIGN KEY (`payMehtodId`)
    REFERENCES `laquena`.`payMehtod` (`payMehtodId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`unit` (
  `unitId` VARCHAR(3) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`unitId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`product` (
  `productId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `iso31661Code` VARCHAR(2) NOT NULL,
  `latitude` DECIMAL(11,7) NULL,
  `longitude` DECIMAL(11,7) NULL,
  `history` NVARCHAR(500) NULL,
  `height` DECIMAL(6,2) NULL,
  `height_unitId` VARCHAR(3) NOT NULL,
  `weight` VARCHAR(45) NULL,
  `weight_unitId` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`productId`),
  INDEX `fk_product_country1_idx` (`iso31661Code` ASC),
  INDEX `fk_product_unit1_idx` (`height_unitId` ASC),
  INDEX `fk_product_unit2_idx` (`weight_unitId` ASC),
  CONSTRAINT `fk_product_country1`
    FOREIGN KEY (`iso31661Code`)
    REFERENCES `laquena`.`country` (`iso31661Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_unit1`
    FOREIGN KEY (`height_unitId`)
    REFERENCES `laquena`.`unit` (`unitId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_unit2`
    FOREIGN KEY (`weight_unitId`)
    REFERENCES `laquena`.`unit` (`unitId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`clasification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`clasification` (
  `clasificationId` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`clasificationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`product_clasification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`product_clasification` (
  `productId` INT NOT NULL,
  `clasificationId` INT NOT NULL,
  PRIMARY KEY (`productId`, `clasificationId`),
  INDEX `fk_product_has_clasification_clasification1_idx` (`clasificationId` ASC),
  INDEX `fk_product_has_clasification_product1_idx` (`productId` ASC),
  CONSTRAINT `fk_product_has_clasification_product1`
    FOREIGN KEY (`productId`)
    REFERENCES `laquena`.`product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_clasification_clasification1`
    FOREIGN KEY (`clasificationId`)
    REFERENCES `laquena`.`clasification` (`clasificationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`price` (
  `productId` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL,
  `price` DECIMAL(8,2) NULL,
  `idCurrency` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`productId`, `idCurrency`),
  INDEX `fk_price_currency1_idx` (`idCurrency` ASC),
  CONSTRAINT `fk_price_product1`
    FOREIGN KEY (`productId`)
    REFERENCES `laquena`.`product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_price_currency1`
    FOREIGN KEY (`idCurrency`)
    REFERENCES `laquena`.`currency` (`idCurrency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laquena`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laquena`.`stock` (
  `establecimientoId` INT NOT NULL,
  `productId` INT NOT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`establecimientoId`, `productId`),
  INDEX `fk_establecimiento_has_product_product1_idx` (`productId` ASC),
  INDEX `fk_establecimiento_has_product_establecimiento1_idx` (`establecimientoId` ASC),
  CONSTRAINT `fk_establecimiento_has_product_establecimiento1`
    FOREIGN KEY (`establecimientoId`)
    REFERENCES `laquena`.`establecimiento` (`establecimientoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_establecimiento_has_product_product1`
    FOREIGN KEY (`productId`)
    REFERENCES `laquena`.`product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
